---
openapi: 3.0.2
info:
  title: Glagol - API for internal use
  version: 1.0.0
servers:
  - url: http://localhost:80/api/internal/v1
    description: Local testing
paths:
  "/page":
    get:
      description: Return Page record
      parameters:
        - name: oid
          required: true
          allowEmptyValue: false
          in: query
          schema:
            type: string
          example: 33361260-b811-4f9f-8c81-2ffab270d758
      responses:
        "200":
          description: OK
          content: # Used for ALL successfull requests. If Page was not found, returns empty object
            application/json:
              schema:
                "$ref": "../packages/schemas/page.json#"
        "400":
          description: OID was not provided or it is not valid
        "500":
          description: Internal server error
